In [1]:
# classification mlp model
from numpy import unique
from numpy import argmax
from pandas import read_csv
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [2]:
#Load Train File (Run this if you are using Jupyter Notebook)
df_train=read_csv('train.csv')
dataset = df_train.values
X, y = dataset[:, 1:-1], dataset[:, -1]

In [ ]:
#Load Train File in Google Drive (Run this if you are using Google Collab)
from google.colab import drive 
drive.mount('/content/gdrive')
# 'gdrive/My Drive/Colab Notebooks/train.csv' -> is the example path of your csv training file in google drive
df_train=read_csv('gdrive/My Drive/Colab Notebooks/train.csv')
dataset = df_train.values
X, y = dataset[:, 1:-1], dataset[:, -1]

In [3]:
print("------------------")
print(X)
print("------------------")
print(y)

------------------
[[-0.04957322  0.05148186  0.06149769 ...  0.9517357  -0.3030943
  -0.133766  ]
 [-0.0852981   0.04864757  0.08326341 ...  0.9181289  -0.3019532
  -0.1112807 ]
 [-0.04656757  0.05779297  0.1149698  ...  0.9588635  -0.2888554
  -0.07875562]
 ...
 [-0.07608207 -0.1209782  -0.06041521 ...  0.9150897  -0.3452695
  -0.05962909]
 [-0.1159183  -0.1091329  -0.075187   ...  0.8749824  -0.3334227
  -0.07303173]
 [-0.09997093 -0.02197526 -0.08667104 ...  0.8906366  -0.2462672
  -0.08313887]]
------------------
[5. 5. 5. ... 2. 2. 2.]


In [4]:
#Change to float, create variable that save number of features (input) 
# and create variable that save number of class (output)
X, y = X.astype('float'), y.astype('float')
n_features = X.shape[1]
y = LabelEncoder().fit_transform(y)
n_class = len(unique(y))

In [5]:
print("Print again after change to float and labeling the output")
print("------------------")
print(X)
print("------------------")
print(y)

Print again after change to float and labeling the output
------------------
[[-0.04957322  0.05148186  0.06149769 ...  0.9517357  -0.3030943
  -0.133766  ]
 [-0.0852981   0.04864757  0.08326341 ...  0.9181289  -0.3019532
  -0.1112807 ]
 [-0.04656757  0.05779297  0.1149698  ...  0.9588635  -0.2888554
  -0.07875562]
 ...
 [-0.07608207 -0.1209782  -0.06041521 ...  0.9150897  -0.3452695
  -0.05962909]
 [-0.1159183  -0.1091329  -0.075187   ...  0.8749824  -0.3334227
  -0.07303173]
 [-0.09997093 -0.02197526 -0.08667104 ...  0.8906366  -0.2462672
  -0.08313887]]
------------------
[4 4 4 ... 1 1 1]


In [6]:
print("------------------")
print(f"n_features {n_features}")
print("------------------")
print(f"n_class {n_class}")

------------------
n_features 9
------------------
n_class 6


In [7]:
#Load TEST FILE and change input and output to float (Run this if you are using Jupyter Notebook)
df_test=read_csv('test.csv')
dataset_test = df_test.values
X_test, y_test = dataset_test[:, 1:-1], dataset_test[:, -1]
X_test, y_test = X_test.astype('float'), y_test.astype('float')
y_test = LabelEncoder().fit_transform(y_test)

In [ ]:
#Load TEST FILE and change input and output to float (Run this if you are using Google Collab)
df_test=read_csv('gdrive/My Drive/Colab Notebooks/test.csv')
dataset_test = df_test.values
X_test, y_test = dataset_test[:, 1:-1], dataset_test[:, -1]
X_test, y_test = X_test.astype('float'), y_test.astype('float')
y_test = LabelEncoder().fit_transform(y_test)

In [8]:
print("Print Test variables")
print("------------------")
print(X_test)
print("------------------")
print(y_test)

Print Test variables
------------------
[[ 0.01165315 -0.02939904  0.1068262  ...  1.041216   -0.2697959
   0.02377977]
 [ 0.01310909 -0.03972867  0.1524549  ...  1.041803   -0.280025
   0.07629271]
 [ 0.01126885 -0.05240586  0.2168462  ...  1.039086   -0.2926631
   0.1474754 ]
 ...
 [-0.07190685 -0.1943222  -0.1275547  ...  0.8980947  -0.3977751
  -0.156105  ]
 [-0.1422088  -0.1470701  -0.09236675 ...  0.8283723  -0.3492473
  -0.1227979 ]
 [-0.1709989  -0.1313991  -0.05112688 ...  0.8002428  -0.3323721
  -0.08357159]]
------------------
[4 4 4 ... 1 1 1]


In [9]:
# define the keras model
model = Sequential()
model.add(Dense(20, input_dim=n_features, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(10, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(n_class, activation='softmax'))
# compile the keras model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=32, verbose=2)

Epoch 1/150
16508/16508 - 9s - loss: 0.4787
Epoch 2/150
16508/16508 - 8s - loss: 0.3699
Epoch 3/150
16508/16508 - 8s - loss: 0.3527
Epoch 4/150
16508/16508 - 8s - loss: 0.3432
Epoch 5/150
16508/16508 - 8s - loss: 0.3349
Epoch 6/150
16508/16508 - 8s - loss: 0.3286
Epoch 7/150
16508/16508 - 8s - loss: 0.3242
Epoch 8/150
16508/16508 - 8s - loss: 0.3212
Epoch 9/150
16508/16508 - 8s - loss: 0.3184
Epoch 10/150
16508/16508 - 8s - loss: 0.3162
Epoch 11/150
16508/16508 - 8s - loss: 0.3141
Epoch 12/150
16508/16508 - 8s - loss: 0.3125
Epoch 13/150
16508/16508 - 8s - loss: 0.3106
Epoch 14/150
16508/16508 - 8s - loss: 0.3089
Epoch 15/150
16508/16508 - 8s - loss: 0.3073
Epoch 16/150
16508/16508 - 8s - loss: 0.3056
Epoch 17/150
16508/16508 - 8s - loss: 0.3038
Epoch 18/150
16508/16508 - 9s - loss: 0.3022
Epoch 19/150
16508/16508 - 8s - loss: 0.3008
Epoch 20/150
16508/16508 - 8s - loss: 0.2998
Epoch 21/150
16508/16508 - 8s - loss: 0.2987
Epoch 22/150
16508/16508 - 8s - loss: 0.2977
Epoch 23/150
16508/

In [10]:
# evaluate on test set
yhat = model.predict(X_test)
yhat = argmax(yhat, axis=-1).astype('int')
acc = accuracy_score(y_test, yhat)
print('Accuracy: %.3f' % acc)

Accuracy: 0.730


In [11]:
# F1 Score
from sklearn.metrics import f1_score
f1 = f1_score(y_test, yhat, average='weighted')
print('F1 score: %f' % f1)

F1 score: 0.730437
